# Generated by Django 5.0.2 on 2024-12-11 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """Migration to create PlumbingDocument, PlumbingImage, and PlumbingTable models."""

    dependencies = [
        ("main", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlumbingDocument",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("json_content", models.JSONField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plumbing_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Plumbing Document",
                "verbose_name_plural": "Plumbing Documents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PlumbingImage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_number", models.IntegerField()),
                ("image", models.ImageField(upload_to="plumbing_code/optimizer/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="main.plumbingdocument",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plumbing Image",
                "verbose_name_plural": "Plumbing Images",
                "ordering": ["page_number"],
            },
        ),
        migrations.CreateModel(
            name="PlumbingTable",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_number", models.IntegerField()),
                ("csv_content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tables",
                        to="main.plumbingdocument",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plumbing Table",
                "verbose_name_plural": "Plumbing Tables",
                "ordering": ["page_number"],
            },
        ),
    ]
