# Generated by Django 5.0.2 on 2024-12-12 13:00

from django.db import migrations, models


class Migration(migrations.Migration):
    """Migration to update model options and image upload paths."""

    dependencies = [
        ("main", "0002_plumbingdocument_plumbingimage_plumbingtable"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="plumbingdocument",
            options={
                "ordering": ["title"],
                "verbose_name": "Plumbing Document",
                "verbose_name_plural": "Plumbing Documents",
            },
        ),
        migrations.AlterModelOptions(
            name="plumbingimage",
            options={
                "ordering": ["document", "page_number"],
                "verbose_name": "Plumbing Image",
                "verbose_name_plural": "Plumbing Images",
            },
        ),
        migrations.AlterModelOptions(
            name="plumbingtable",
            options={
                "ordering": ["document", "page_number"],
                "verbose_name": "Plumbing Table",
                "verbose_name_plural": "Plumbing Tables",
            },
        ),
        migrations.AlterField(
            model_name="plumbingdocument",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="plumbingimage",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="plumbingimage",
            name="image",
            field=models.ImageField(upload_to="plumbing_code/final_jpg/"),
        ),
        migrations.AlterField(
            model_name="plumbingtable",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
