"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path
from typing import Any, Dict, List, Optional, Union

from django.core.exceptions import ImproperlyConfigured
from django.core.management.utils import get_random_secret_key
from dotenv import load_dotenv


# Environment variable utilities
def get_env_value(env_variable: str, default: Any = None, required: bool = False) -> Any:
    """Get an environment variable or return its default."""
    value = os.getenv(env_variable)
    if value is None and required:
        raise ImproperlyConfigured(f"Environment variable {env_variable} is required.")
    return value if value is not None else default


def get_bool_env(env_variable: str, default: bool = False) -> bool:
    """Get a boolean environment variable."""
    value = get_env_value(env_variable, default=str(default))
    return value.lower() in ("true", "t", "1", "yes", "y")


def get_int_env(env_variable: str, default: int = 0) -> int:
    """Get an integer environment variable."""
    value = get_env_value(env_variable, default=default)
    try:
        return int(value)
    except (TypeError, ValueError):
        return default


def get_list_env(env_variable: str, default: List[str] = None, separator: str = ",") -> List[str]:
    """Get a list from an environment variable."""
    if default is None:
        default = []
    value = get_env_value(env_variable)
    if value is None:
        return default
    return [item.strip() for item in value.split(separator) if item.strip()]


# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/


# SECURITY WARNING: keep the secret key used in production secret!
def generate_secret_key() -> str:
    """Generate a secure secret key."""
    key = get_random_secret_key()
    with open(BASE_DIR / ".secret_key", "w") as f:
        f.write(key)
    return key


def get_secret_key() -> str:
    """Get or generate the secret key."""
    # Try to get from environment
    key = get_env_value("SECRET_KEY")
    if key:
        return key

    # Try to get from file
    key_file = BASE_DIR / ".secret_key"
    if key_file.exists():
        return key_file.read_text().strip()

    # Generate new key
    return generate_secret_key()


SECRET_KEY = get_secret_key()

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = get_bool_env("DEBUG", default=False)

ALLOWED_HOSTS = get_list_env("ALLOWED_HOSTS", default=["localhost", "127.0.0.1"])

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third party apps
    "crispy_forms",
    "crispy_bootstrap5",
    "corsheaders",
    # Local apps
    "main",
]

# Crispy Forms
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # Whitenoise for static files
    "corsheaders.middleware.CorsMiddleware",  # CORS headers
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": ("django.contrib.auth.password_validation." "UserAttributeSimilarityValidator"),
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Media files (User uploaded files)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Plumbing code media subdirectories
PLUMBING_CODE_DIR = MEDIA_ROOT / "plumbing_code"
PLUMBING_CODE_DIRS = {
    "ocr": PLUMBING_CODE_DIR / "OCR",
    "embeddings": PLUMBING_CODE_DIR / "embeddings",
    "json": PLUMBING_CODE_DIR / "json",
    "json_final": PLUMBING_CODE_DIR / "json_final",
    "json_processed": PLUMBING_CODE_DIR / "json_processed",
    "tables": PLUMBING_CODE_DIR / "tables",
    "analytics": PLUMBING_CODE_DIR / "analytics",
    "optimizer": PLUMBING_CODE_DIR / "optimizer",
    "original": PLUMBING_CODE_DIR / "original",
    "uploads": PLUMBING_CODE_DIR / "uploads",
}

# Create directories if they don't exist
for directory in [MEDIA_ROOT, PLUMBING_CODE_DIR, *PLUMBING_CODE_DIRS.values()]:
    directory.mkdir(parents=True, exist_ok=True)

# CORS Configuration
CORS_ALLOW_ALL_ORIGINS = False  # Don't allow all origins in production
CORS_ALLOWED_ORIGINS = get_list_env(
    "CORS_ALLOWED_ORIGINS", default=["http://localhost:8000", "http://127.0.0.1:8000"]
)

# Authentication settings
LOGIN_REDIRECT_URL = "/profile/"  # Redirect to profile page after login
LOGOUT_REDIRECT_URL = "/home/"  # Redirect to home page after logout
LOGIN_URL = "login"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Email Configuration
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = get_env_value("EMAIL_HOST", "localhost")
EMAIL_PORT = get_int_env("EMAIL_PORT", 587)
EMAIL_HOST_USER = get_env_value("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = get_env_value("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = get_env_value("DEFAULT_FROM_EMAIL", EMAIL_HOST_USER)

# Required API Keys - validate on startup
REQUIRED_API_KEYS = {
    "OPEN_API_KEY": get_env_value("OPEN_API_KEY", required=True),
    "GROQ_API_KEY": get_env_value("GROQ_API_KEY", required=True),
    "PINE_API_KEY": get_env_value("PINE_API_KEY", required=True),
}

# Optional API Keys - don't fail if missing
OPTIONAL_API_KEYS = {
    "NEWS_API_KEY": get_env_value("NEWS_API_KEY"),
    "TUBE_API_KEY": get_env_value("TUBE_API_KEY"),
    "LAMA_API_KEY": get_env_value("LAMA_API_KEY"),
    "HUGG_API_KEY": get_env_value("HUGG_API_KEY"),
    "PLEX_API_KEY": get_env_value("PLEX_API_KEY"),
}


# API URLs with validation
def get_api_url(name: str, default: str) -> str:
    """Get an API URL with validation."""
    url = get_env_value(f"{name}_API_URL", default)
    if not url.startswith(("http://", "https://")):
        raise ImproperlyConfigured(f"{name}_API_URL must be a valid HTTP(S) URL")
    return url


API_URLS = {
    "HUGG": get_api_url(
        "HUGG", "https://api-inference.huggingface.co/models/microsoft/speecht5_tts"
    ),
    "PLEX": get_api_url("PLEX", "https://api.perplexity.ai/chat/completions"),
}

# Logging Configuration
LOGS_DIR = BASE_DIR / "logs"
LOGS_DIR.mkdir(parents=True, exist_ok=True)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {"format": "%(asctime)s - %(name)s - %(levelname)s - %(message)s"},
        "simple": {"format": "%(levelname)s %(message)s"},
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
            "level": "INFO",
        },
        "file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": LOGS_DIR / "django.log",
            "maxBytes": 10 * 1024 * 1024,  # 10MB
            "backupCount": 5,
            "formatter": "verbose",
            "level": "INFO",
        },
        "image_processing": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": LOGS_DIR / "image_processing.log",
            "maxBytes": 10 * 1024 * 1024,  # 10MB
            "backupCount": 5,
            "formatter": "verbose",
            "level": "INFO",
        },
        "mail_admins": {
            "class": "django.utils.log.AdminEmailHandler",
            "level": "ERROR",
            "formatter": "verbose",
            "include_html": True,
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console", "file", "mail_admins"],
            "level": "INFO",
            "propagate": True,
        },
        "main": {
            "handlers": ["console", "file"],
            "level": "INFO",
            "propagate": True,
        },
        "main.utils.process_image": {
            "handlers": ["console", "image_processing"],
            "level": "INFO",
            "propagate": False,
        },
    },
}
